import type { Metadata } from "next";
import { Outfit } from 'next/font/google'
import { Pixelify_Sans } from "next/font/google";
import "./globals.css";
import { QueryClient, QueryClientProvider } from "@tanstack/react-query";
import { Providers } from "./provider";

const outfit = Outfit({
  subsets: ['latin'],
  variable: '--font-outfit',
})


const pixelify = Pixelify_Sans({
  subsets: ["latin"],
  weight: ["400", "700"],
  variable: "--font-pixelify",
});


export const metadata: Metadata = {
  title: "Neural Email Assistant",
  description: "Generated by create next app",
};

// const queryClient = new QueryClient();

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <Providers>
          {children}
        </Providers>

      </body>

    </html>
  );
}
